use_frameworks!

abstract_target 'TweetieAbstract' do

    pod 'Alamofire'

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RealmSwift'
    pod 'RxRealm'
    pod 'Unbox'
    pod 'Then'
    pod 'Reachability'
    pod 'Kingfisher'
    pod 'RxRealmDataSources'

    target 'Tweetie' do
        pod 'RxDataSources'
    end
    
    target 'MacTweetie' do
    end
    
    target 'TweetieTests' do
        pod 'RxTest'
        pod 'RxBlocking'
    end
end
